<a href="https://colab.research.google.com/github/Seyam-12/Data_science/blob/main/Mohammed_Sadik_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
# i is set from 0 to 99 the range is 100.

In [2]:
for i in range(5,8):
    print(i)

5
6
7


In [ ]:
# i value set fron 5 to 8.

In [4]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


In [ ]:
# new code have been added. with the i value the new pring is "test number" now the outcome says test number and the whatever number it is command to.

### Functions

In [3]:
def square(x):
    return x**2

In [ ]:
# square have been set a x**2 or square(x) where the x represent different variable.

In [5]:
square(5)

25

In [ ]:
# 5 have replace x and 5 square is 25 as the outcome is showing.

In [7]:
square(square(2))

16

In [ ]:
# the one extra parenthese represents one more exponent, in this case its 2 squared and then the outcome is squared again as the outcome is showing 16.

In [ ]:
square(square(square(2)))


256

In [ ]:
# this is 2 squared 3 times which mean 2 to the power of 6 and the outcome is 256.

In [ ]:
square(123456)

15241383936

In [ ]:
# this is the outcome of 123456 squared

In [ ]:
square(square(5))

625

In [ ]:
# thsi code mean that 5 to the power of 4

In [ ]:
def add_two(x):
    return x+2

In [ ]:
# this code is x+2 where x represents different values.

In [ ]:
add_two(5)

7

In [ ]:
# this is where 2 added to 5 which is 7.

In [ ]:
square(add_two(5))

49

In [ ]:
# this code is 5+2 is 7 then the squared of the outcome 7 is 49

### Logical Branching

In [9]:
choice = "apple"

In [11]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [ ]:
# this code shown that choise is set as apple and if the choice is apple then print you choose apple if not then pring yoy did not choose apple.

In [12]:
choice = "orange"

In [13]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
# this is the exact same code as the previous one just apple have been replaced by orange and the outcome is you did not choose apple.

In [14]:
choice = "apple"

In [15]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


In [ ]:
# the choice  is apple and new code is added is you choose apple.

### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

In [ ]:
# this code gives an option as please enter your choice as input.

In [ ]:
choice

'oranges'

In [ ]:
# the choice is orange

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


In [ ]:
# choice is set a oranges and the commad is is whatever is the choice berween apples and oranges outcome should be that and if not then say you did not choose apples or oranges.

#### Coins

In [ ]:
np.random.random()

In [ ]:
# np is set as random.

In [ ]:
np.random.random() > 0.5

In [ ]:
# the random is restricted to more than 0.5 and less than 1

In [ ]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [ ]:
# it set as if the np is more than 0.5 then the outcome should say heads and if it’s less that that it should print tails.

In [ ]:
flip_coin()

### Graphics Output

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
display(HTML('<h1>Hello, world!</h1>'))

In [ ]:
def coin():
  return np.random.randint(2)

In [ ]:
coin()

In [ ]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [ ]:
# the url of coin

In [ ]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [ ]:
# url of both side of the coin.

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
show_img(heads)

In [ ]:
show_img(tails)

In [ ]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [ ]:
# new code is that now show the picture of heads or tails rather that just printing.

In [ ]:
flip_coin()

In [ ]:
for i in range(5):
    flip_coin()

In [ ]:
# coin flip 5 times.

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [ ]:
# code for deck of playing cards.

In [ ]:
a = np.arange(52)

In [ ]:
# there are 52 cards in a deck

In [ ]:
shuffle(a)

In [ ]:
np.random.permutation(52)

In [ ]:
# code for random pick.

### Speed Test

In [ ]:
%%timeit
shuffle(a)

In [ ]:
# how fast it can shuffle

In [ ]:
%%timeit
np.random.permutation(52)

In [ ]:
# randomly shuffle all 52 cards.

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([51, 40, 39,  2, 19, 24, 12,  7, 14, 28,  8, 21, 18, 49, 47, 27,  1,
       44, 10, 16, 42,  3, 43, 31, 46, 29, 38,  4, 23,  5, 50, 35, 41, 36,
       11, 13, 34, 15, 32, 26, 45, 20, 48, 30,  9, 17, 33,  0, 22, 25,  6,
       37])

In [ ]:
# show cards in random order.

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards

array([32,  0, 51, 29, 27, 15, 39, 45, 42, 12, 30, 28, 44, 34, 33, 16, 49,
       47,  6, 22, 40, 24, 10, 21, 11, 23, 41, 48,  5, 36, 13, 46, 31, 17,
        7, 14,  1, 26,  2, 43, 25,  4, 35, 18,  8, 37, 50,  9,  3, 38, 20,
       19])

In [ ]:
# show cards in random order.

In [ ]:
cards[0]

32

In [ ]:
# the first card was the 32nd one

In [ ]:
cards[1]

0

In [ ]:
# the second card was the first one.

In [ ]:
cards[2]

51

In [ ]:
#the 3rd card was the 51st one.

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
# picture of all 52 cards

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
# the command is to reshapw then in 4 rows of 13

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
# different name of the cards.

In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


In [ ]:
# the name of the card is printed also with the cards whiuch one it is.

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
# the url of cards

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
# all the different values of the cards.

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
# random pick of cards.

In [ ]:
i,j

(0, 11)

In [ ]:
# the i and j is the first and twelfth cards.

In [ ]:
suit[i]

'k'

In [ ]:
# i is king

In [ ]:
card[j]

'q'

In [ ]:
# card j is the queen

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
# showing the picture od the picked card

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
# card 3 is the k4

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
# showing the picture od the picked card

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

In [ ]:
# showing the picture od the picked card